Specific Error message in commit note
Epoch: 0
  0%|          | 1/1366 [00:00<09:06,  2.50it/s]
Loss: 91.48601531982422
  7%|▋         | 101/1366 [00:45<09:31,  2.21it/s]
Loss: 79.26459724124115
 15%|█▍        | 201/1366 [01:30<08:26,  2.30it/s]
Loss: 77.93476367589847
 22%|██▏       | 301/1366 [02:16<08:12,  2.16it/s]
Loss: 77.3081855076888
 29%|██▉       | 401/1366 [03:01<07:11,  2.24it/s]
Loss: 76.72255608327966
 37%|███▋      | 501/1366 [03:47<05:56,  2.43it/s]
Loss: 76.47353506564143
 44%|████▍     | 601/1366 [04:32<05:46,  2.21it/s]
Loss: 75.8702592929072
 51%|█████▏    | 701/1366 [05:17<04:52,  2.28it/s]
Loss: 75.56331405149886
 59%|█████▊    | 801/1366 [06:02<04:09,  2.27it/s]
Loss: 75.32485449715946
 66%|██████▌   | 901/1366 [06:47<03:36,  2.15it/s]
Loss: 74.93786456608746
 73%|███████▎  | 1001/1366 [07:33<02:55,  2.08it/s]
Loss: 74.57818475279298
 81%|████████  | 1101/1366 [08:18<01:54,  2.32it/s]
Loss: 74.24359037484179
 88%|████████▊ | 1201/1366 [09:03<01:14,  2.20it/s]
Loss: 74.29219537809628
 95%|█████████▌| 1301/1366 [09:49<00:28,  2.26it/s]
Loss: 74.25435785767118
100%|██████████| 1366/1366 [10:18<00:00,  2.21it/s]
  0%|          | 6/1669 [00:14<1:07:22,  2.43s/it]
/home/chia/.cache/huggingface/modules/evaluate_modules/metrics/evaluate-metric--mean_iou/08bc20f4f895f3caf75fb9e3fada1404bded3c3265243d05327cbb3b9326ffe9/mean_iou.py:259: RuntimeWarning: invalid value encountered in divide
  iou = total_area_intersect / total_area_union
/home/chia/.cache/huggingface/modules/evaluate_modules/metrics/evaluate-metric--mean_iou/08bc20f4f895f3caf75fb9e3fada1404bded3c3265243d05327cbb3b9326ffe9/mean_iou.py:260: RuntimeWarning: invalid value encountered in divide
  acc = total_area_intersect / total_area_label
Mean IoU: 0.05507502392472341
Epoch: 1
  0%|          | 1/1366 [00:00<09:02,  2.52it/s]
Loss: 74.19892582617804
  7%|▋         | 101/1366 [00:38<08:04,  2.61it/s]
Loss: 74.06253324403353
 15%|█▍        | 201/1366 [01:17<07:21,  2.64it/s]
Loss: 73.97869282584321
 22%|██▏       | 301/1366 [01:55<06:53,  2.57it/s]
Loss: 73.94232762982621
 29%|██▉       | 401/1366 [02:34<06:43,  2.39it/s]
Loss: 73.68397578426722
 37%|███▋      | 501/1366 [03:13<05:46,  2.50it/s]
Loss: 73.65636272563229
 44%|████▍     | 601/1366 [03:52<04:51,  2.62it/s]
Loss: 73.50030964500843
 51%|█████▏    | 701/1366 [04:31<04:19,  2.56it/s]
Loss: 73.4535749783306
 59%|█████▊    | 801/1366 [05:10<03:39,  2.57it/s]
Loss: 73.31332071178456
 66%|██████▌   | 901/1366 [05:49<03:02,  2.55it/s]
Loss: 73.1659493002536
 73%|███████▎  | 1001/1366 [06:28<02:22,  2.57it/s]
Loss: 73.01658364131977
 75%|███████▍  | 1023/1366 [06:36<02:12,  2.58it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[24], line 14
     12 print("Epoch:", epoch)
     13 model.train()
---> 14 for idx, batch in enumerate(tqdm(train_dataloader)): # this iterates through all the batches. one for loop = one batch is put through the training loop. train_dataloader is loading in the batches
     15     # Reset the parameter gradients
     16     optimizer.zero_grad()
     18     # Forward pass

File ~/anaconda3/envs/bizon_py39/lib/python3.9/site-packages/tqdm/std.py:1178, in tqdm.__iter__(self)
   1175 time = self._time
   1177 try:
-> 1178     for obj in iterable:
   1179         yield obj
   1180         # Update and possibly print the progressbar.
   1181         # Note: does not call self.update(1) for speed optimisation.

File ~/anaconda3/envs/bizon_py39/lib/python3.9/site-packages/torch/utils/data/dataloader.py:633, in _BaseDataLoaderIter.__next__(self)
    630 if self._sampler_iter is None:
    631     # TODO(https://github.com/pytorch/pytorch/issues/76750)
    632     self._reset()  # type: ignore[call-arg]
--> 633 data = self._next_data()
    634 self._num_yielded += 1
    635 if self._dataset_kind == _DatasetKind.Iterable and \
    636         self._IterableDataset_len_called is not None and \
    637         self._num_yielded > self._IterableDataset_len_called:

File ~/anaconda3/envs/bizon_py39/lib/python3.9/site-packages/torch/utils/data/dataloader.py:677, in _SingleProcessDataLoaderIter._next_data(self)
    675 def _next_data(self):
    676     index = self._next_index()  # may raise StopIteration
--> 677     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    678     if self._pin_memory:
    679         data = _utils.pin_memory.pin_memory(data, self._pin_memory_device)

File ~/anaconda3/envs/bizon_py39/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py:54, in _MapDatasetFetcher.fetch(self, possibly_batched_index)
     52 else:
     53     data = self.dataset[possibly_batched_index]
---> 54 return self.collate_fn(data)

Cell In[15], line 61, in custom_collate_fn(batch)
     58 images = inputs[0]
     59 segmentation_maps = inputs[1]
---> 61 batch = processor(
     62     images,
     63     segmentation_maps=segmentation_maps,
     64     return_tensors="pt",
     65 )
     67 batch["original_images"] = inputs[2]
     68 batch["original_segmentation_maps"] = inputs[3]

File ~/anaconda3/envs/bizon_py39/lib/python3.9/site-packages/transformers/models/mask2former/image_processing_mask2former.py:542, in Mask2FormerImageProcessor.__call__(self, images, segmentation_maps, **kwargs)
    541 def __call__(self, images, segmentation_maps=None, **kwargs) -> BatchFeature:
--> 542     return self.preprocess(images, segmentation_maps=segmentation_maps, **kwargs)

File ~/anaconda3/envs/bizon_py39/lib/python3.9/site-packages/transformers/models/mask2former/image_processing_mask2former.py:718, in Mask2FormerImageProcessor.preprocess(self, images, segmentation_maps, instance_id_to_semantic_id, do_resize, size, size_divisor, resample, do_rescale, rescale_factor, do_normalize, image_mean, image_std, ignore_index, reduce_labels, return_tensors, data_format, **kwargs)
    713 if segmentation_maps is not None:
    714     segmentation_maps = [
    715         self._preprocess_mask(segmentation_map, do_resize, size, size_divisor)
    716         for segmentation_map in segmentation_maps
    717     ]
--> 718 encoded_inputs = self.encode_inputs(
    719     images, segmentation_maps, instance_id_to_semantic_id, ignore_index, reduce_labels, return_tensors
    720 )
    721 return encoded_inputs

File ~/anaconda3/envs/bizon_py39/lib/python3.9/site-packages/transformers/models/mask2former/image_processing_mask2former.py:864, in Mask2FormerImageProcessor.encode_inputs(self, pixel_values_list, segmentation_maps, instance_id_to_semantic_id, ignore_index, reduce_labels, return_tensors, **kwargs)
    862     instance_id = instance_id_to_semantic_id
    863 # Use instance2class_id mapping per image
--> 864 masks, classes = self.convert_segmentation_map_to_binary_masks(
    865     segmentation_map, instance_id, ignore_index=ignore_index, reduce_labels=reduce_labels
    866 )
    867 # We add an axis to make them compatible with the transformations library
    868 # this will be removed in the future
    869 masks = [mask[None, ...] for mask in masks]

File ~/anaconda3/envs/bizon_py39/lib/python3.9/site-packages/transformers/models/mask2former/image_processing_mask2former.py:534, in Mask2FormerImageProcessor.convert_segmentation_map_to_binary_masks(self, segmentation_map, instance_id_to_semantic_id, ignore_index, reduce_labels)
    532 reduce_labels = reduce_labels if reduce_labels is not None else self.reduce_labels
    533 ignore_index = ignore_index if ignore_index is not None else self.ignore_index
--> 534 return convert_segmentation_map_to_binary_masks(
    535     segmentation_map=segmentation_map,
    536     instance_id_to_semantic_id=instance_id_to_semantic_id,
    537     ignore_index=ignore_index,
    538     reduce_labels=reduce_labels,
    539 )

File ~/anaconda3/envs/bizon_py39/lib/python3.9/site-packages/transformers/models/mask2former/image_processing_mask2former.py:278, in convert_segmentation_map_to_binary_masks(segmentation_map, instance_id_to_semantic_id, ignore_index, reduce_labels)
    276 # Generate a binary mask for each object instance
    277 binary_masks = [(segmentation_map == i) for i in all_labels]
--> 278 binary_masks = np.stack(binary_masks, axis=0)  # (num_labels, height, width)
    280 # Convert instance ids to class ids
    281 if instance_id_to_semantic_id is not None:

File ~/anaconda3/envs/bizon_py39/lib/python3.9/site-packages/numpy/core/shape_base.py:445, in stack(arrays, axis, out, dtype, casting)
    443 arrays = [asanyarray(arr) for arr in arrays]
    444 if not arrays:
--> 445     raise ValueError('need at least one array to stack')
    447 shapes = {arr.shape for arr in arrays}
    448 if len(shapes) != 1:

ValueError: need at least one array to stack